name: kajimini
description: Aplikasi Kajimini Pribadiku
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  flutter_markdown: ^0.6.18
  file_picker: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.2 # <--- Paket baru untuk menyimpan API Key

flutter:
  uses-material-design: true