name: Build and Release Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Generate Android Folder (Kajimini)
        run: |
          flutter create --org com.kajimini --project-name kajimini temp_project
          cp -r temp_project/android ./android
          rm -rf temp_project

      - name: Inject Internet Permission (Solusi SocketException)
        # Robot akan menyisipkan izin internet ke dalam file AndroidManifest
        run: |
          sed -i 's/<application/<uses-permission android:name="android.permission.INTERNET" \/>\n    <application/g' android/app/src/main/AndroidManifest.xml

      - name: Auto-Generate Keystore & Inject Signer (PERBAIKAN)
        run: |
          # 1. Buat Keystore Digital
          keytool -genkey -v -keystore android/app/kajimini.jks -keyalg RSA -keysize 2048 -validity 10000 -alias kajimini -storepass kajimini123 -keypass kajimini123 -dname "CN=Kajimini, OU=Dev, O=Kajimini, L=Jakarta, ST=DKI, C=ID"
          
          # 2. Suntikkan konfigurasi secara presisi ke dalam kurung 'android' menggunakan AWK
          awk '/buildTypes \{/ { print "    signingConfigs {\n        release {\n            storeFile file(\"kajimini.jks\")\n            storePassword \"kajimini123\"\n            keyAlias \"kajimini\"\n            keyPassword \"kajimini123\"\n        }\n    }" } 1' android/app/build.gradle > temp.gradle
          mv temp.gradle android/app/build.gradle
          
          # 3. Ubah config debug menjadi release
          sed -i 's/signingConfig signingConfigs.debug/signingConfig signingConfigs.release/g' android/app/build.gradle

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Signed APK (Resmi Berlisensi & Bisa Internet)
        run: flutter build apk --release

      - name: Upload APK ke GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: Kajimini-App-Release
          path: build/app/outputs/flutter-apk/app-release.apk